/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'keyhan' at '2016-11-02 11:05' with Gradle 2.14.1
 *
 * @author keyhan, @date 2016-11-02 11:05
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
